spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  application:
    name: wisecamp

  datasource:
    url: ${DEV_DB_URL:jdbc:postgresql://localhost:5432/wisecamp-dev}
    username: ${DEV_DB_USERNAME:postgres}
    password: ${DEV_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: prod

  application:
    name: wisecamp

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
